// USER 
export const LOGIN_USER = "LOGIN_USER";

// JOBS
export const RECIVE_JOBS = "RECIVE_JOBS"
export const FETCH_JOBS = "FETCH_JOBS";
export const FILTERD_JOBS = "FILTERD_JOBS"

// CLEAR FILTER
export const CLEAR_USER_JOB_FILTER_SELECTIONS = "CLEAR_USER_JOB_FILTER_SELECTIONS"

// ORGANIZATIONS
export const ADD_SELECTED_ORGANIZATIONS = "ADD_SELECTED_ORGANIZATIONS";
export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const INCLUDE_JOBS_BY_ORGANIZATION = "INCLUDE_JOBS_BY_ORGANIZATION" 
export const INCLUDE_JOB_BY_ORGANIZATION = "INCLUDE_JOB_BY_ORGANIZATION" 

// JOB TYPES
export const ADD_SELECTED_JOB_TYPES = "ADD_SELECTED_JOB_TYPES";
export const UNIQUE_JOB_TYPES = "UNIQUE_JOB_TYPES"
export const INCLUDE_JOBS__BY_JOB_TYPES = "INCLUDE_JOBS__BY_JOB_TYPES" 
export const INCLUDE_JOB__BY_JOB_TYPES = "INCLUDE_JOB__BY_JOB_TYPES" 

// JOB DEGREES
export const RECEVIE_DEGREES = "RECEVIE_DEGREES"
export const FETCH_DEGREES = "FETCH_DEGREES"
export const UNIQUE_DEGREES = "UNIQUE_DEGREES"
export const INCLUDE_JOB_BY_DEGREE = "INCLUDE_JOB_BY_DEGREE"
export const ADD_SELECTED_DEGREE = "ADD_SELECTED_DEGREE";

// SKILLS AND SEARCH TERM
export const UPDATE_SKILLS_SEARCH_TERM = "UPDATE_SKILLS_SEARCH_TERM"
export const INCLUDE_JOB_BY_SKILL = "INCLUDE_JOB_BY_SKILL"

